# Generated by Django 3.0.2 on 2020-02-01 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes', '0003_auto_20200201_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=300)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_comments', to='memes.Meme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'meme_comments',
            },
        ),
    ]
