# Generated by Django 3.0.2 on 2020-02-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20200130_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='body',
            field=models.TextField(max_length=300),
        ),
    ]
